# Generated by Django 4.1.7 on 2023-04-06 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_upvote_delete_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='comment',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='main_app.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upvote',
            name='isclicked',
            field=models.BooleanField(default=False),
        ),
    ]
