# Generated by Django 4.1.7 on 2023-04-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_upvote_comment_upvote_isclicked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='post',
        ),
    ]
